### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-siren-action#1]
Original issue: https://github.com/formly-js/angular-formly/issues/338

@XVincentX expressed initial interest in integrating angular-formly with @kevinswiber's [siren](https://github.com/kevinswiber/siren) library. If anyone else is interested in contributing, please comment here.

**Comment by XVincentX** [comment]
Thanks!

Just for the sake of precision, siren is not a library, but a hypermedia specification for representing entities. Probably it is the only one supporting the actions (and thus, worth to integrate with formly), and is the most famous with **HAL** and **CJ**.

But yes, basically the idea is to extrapolate my work (once finished) and contribute back to this project.

**Comment by kevinswiber** [comment]
Hey, this is cool.

@gavriguy I know you've forked the Siren browser project for Applicaster[1].  That project uses Angular.  Would something like this potentially be helpful to you?

[1] https://github.com/applicaster/siren-browser

**Comment by gavriguy** [comment]
hi @kevinswiber thanks for your mentions. we mainly use the siren browser to have a simple ui to test apis we are building. But as an initiative i really like it and will happily help and see where it leads us

**Comment by XVincentX** [comment]
Great guys.
Actually, the aim is to port the form that you can see [here](http://pollsapiclient.herokuapp.com) to formly, feeding it with the siren action returned by the server.

I plan to start working on it this week (or the next one).
I'll try to keep you updated.

**Comment by XVincentX** [comment]
News:

The project is almost complete, and you can find deployed version on the [same](http://pollsapiclient.herokuapp.com) url.

After some final polishing, I'll try to extract the stuff from siren actions. Bear with me!

**Comment by kentcdodds** [comment]
Awesome!

I don't know if you noticed, but I added a feature in [6.14.0](https://github.com/formly-js/angular-formly/blob/master/CHANGELOG.md#6140) that allows you to specify a `fieldTransform` which should make accomplishing this much simpler. Let me know if you have any questions.

**Comment by gavriguy** [comment]
@XVincentX cool

**Comment by XVincentX** [comment]
@kentcdodds 
So, I finally found some time to kick off the module.
Looking at changelog, looks like `fieldTransform` is a simple option to pass to the directive. Given that, my implementation should just be a function. So, it should not be an angular module and neither have got any kind of dependency with formly itself.

Do you agree or am I missing something?

**Comment by kentcdodds** [comment]
I agree. Though I don't see how useful it could be without angular-formly so I would recommend making angular-formly a `peerDependency` as: `angular-formly: '>=6.14.0'` so people get a warning when trying to install it without a version of angular-formly that supports the `fieldTransform` feature your library will utilize.

Also, as a note, a `fieldTransform` can also be placed on `formlyConfig.extras` so it doesn't have to be passed to the directive. That said I envision you creating the function and exporting that with this library, then people hook it up to their own `formlyConfig` or passing it as an option to the individual form.

**Comment by XVincentX** [comment]
I don't know; the thing is that `peerDependency` is going to be deprecated in npm 3;
Perhaps this should not be a npm package, but a git submodule for main `formly` package?

**Comment by kentcdodds** [comment]
It is not going to be deprecated. It's behavior will be improved. And I definitely don't want to make it a git submodule.

**Comment by XVincentX** [comment]
> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

Are you ok with this behaviour?

**Comment by kentcdodds** [comment]
Yep, this is better behavior.

**Comment by XVincentX** [comment]
@kentcdodds #2

**Comment by kentcdodds** [comment]
Alright, it's been merged. Feel free to publish it!

**Comment by XVincentX** [comment]
@kentcdodds Some little things are missing yet. I'll try to follow up with a final release as soon as possible.

I am sorry for the delay, but I have two conference to prepare, and I am a bit busy!

**Comment by kentcdodds** [comment]
Take your time. I personally don't need this library, but I hope others (and you) benefit from what you're building!
